
version: "3"

services:
  springmvc:
    image: spring-mvc
    platform: linux/amd64
    volumes:
      - /tmp:/tmp
    networks:
      - network   
    ports:
      - 8080    
    restart: always     
  lb:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
    - springmvc
    ports:
    - "80:5000"
    - "1936:1936"
    environment:
      BACKENDS: "springmvc:8080"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"
      COOKIES_ENABLED: "true"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge
